name: PHP Deploy FTP

on:
  pull_request:
    branches: 
      - master

permissions:
  contents: read

jobs:
  web-deploy:
    name:  Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Obteniendo rama Master
      uses: actions/checkout@v2
    
    - name: Publicando en FTP
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ftp.joseantoniomarquez.me
        username: github@joseantoniomarquez.me
        password: k4iOTZ6A^6l6BPS*wznwuez36
#  build:

#    runs-on: ubuntu-latest

#    steps:
#    - uses: actions/checkout@v3

#    - name: Validate composer.json and composer.lock
#      run: composer validate --strict

#    - name: Cache Composer packages
#      id: composer-cache
#      uses: actions/cache@v3
#      with:
#        path: vendor
#        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
#        restore-keys: |
#          ${{ runner.os }}-php-

#    - name: Install dependencies
#      run: composer install --prefer-dist --no-progress

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test
    

