name: PHP Deploy FTP

on:
  push:
    branches: 
      - master

permissions:
  contents: read

jobs:
  web-deploy:
    name:  Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Obteniendo rama Master
      uses: actions/checkout@v2
    
    - name: Publicando en FTP
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ${{ secrets.SERVER_SECRET }}
        username: ${{ secrets.USERNAME_SECRET }}
        password: ${{ secrets.PASSWORD_SECRET }}
