on: push
name: Deploy website on push
jobs:
  web-deploy:
    name:  Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Obteniendo rama Master
      uses: actions/master
    
    - name: Publicando en FTP
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ftp.joseantoniomarquez.me
        username: github@joseantoniomarquez.me
        password: k4iOTZ6A^6l6BPS*wznwuez36
